#Diurno

3. Mutações vantajosas geralmente aumentam de
frequência, chegando à fixação. Por outro lado, mutações
deletérias tipicamente são removidas da população pela seleção
natural. Mas em populações reais isso nem sempre ocorre. Descreva
dois processos que podem levar tanto à perda de mutações vantajosas,
quanto à fixação das mutações desvantajosas.

[2 pontos] Pelos menos 2 dos seguintes processos e nenhum erro conceitual:

- Carona genética
- Seleção de fundo
- Deriva genética
- Seleção sexual

[1.75 ponto] Dois dos processos e um erro conceitual leve

Erros conceituais leves comuns:

 - confundir fitness com sobrevivência
 - ignorar o papel da seleção em populações pequenas

[1.5 ponto] Dois dos processos e um erro conceitual grave

Erros conceituais graves comuns:

 - Tratar deriva como um processo determinístico
 - tratar deriva como um processo seletivo

[1 ponto] Um dos processos acima e nenhum erro conceitual

[0.75 ponto] Um dos processos e um erro conceitual leve

[0.5 ponto] Um dos processos e um erro conceitual grave

[0 prontos] Nenhum dos processos acima
:
4. Considere uma amostra populacional, em que os cromossomos
X de uma amostra de 100 homens foi analisada para dois genes bialélicos
(A, a e B, b). As frequências encontradas para as combinações de
alelos foi a seguinte:

Gametas
-------- ---
$f_{AB}$ 0,4
$f_{Ab}$ 0,0
$f_{aB}$ 0,1
$f_{ab}$ 0,5
-------- ---

a)  Quantifique o coeficiente de desequilíbrio de ligação (D) nessa amostra.

Gametas      Alelos
-------- --- ------- ---
$f_{AB}$ 0,4 $f_{A}$ 0,4
$f_{Ab}$ 0,0 $f_{a}$ 0,6
$f_{aB}$ 0,1 $f_{B}$ 0,5
$f_{ab}$ 0,5 $f_{b}$ 0,5
-------- --- ------- ---

$$
D_{AB} = F_{AB} - F_{A} \times F_{B} = 0.4 - 0.4 \times 0.5 = 0.2
$$
$$
D_{Ab} = F_{Ab} - F_{A} \times F_{b} = 0.0 - 0.4 \times 0.5 = -0.2
$$
$$
D_{aB} = F_{aB} - F_{a} \times F_{B} = 0.1 - 0.6 \times 0.5 = -0.2
$$
$$
D_{ab} = F_{ab} - F_{a} \times F_{b} = 0.5 - 0.6 \times 0.5 = 0.2
$$

[1 ponto] Qualquer um dos Ds calculado corretamente
[0.5 pontos] Frequências alélicas calculadas corretamente

b)  Discuta possíveis processos que explicam o surgimento de desequilíbrio de ligação.

[1 ponto] Qualquer dois dos seguintes processos:

- Mutações recentes
- Carona genética
- Migração
- Seleção de associações vantajosas
- Ausência de recombinação
- Proximidade no cromossomo

[0.5 pontos] Qualquer um dos processos acima

# Noturno

6. Defina o conceito de “desequilíbrio de ligação”. Descreva
como podemos quantificá-lo, e apresente dois processos que são capazes
de explicar seu surgimento em populações.

Da aula: “Desequilíbrio de ligação ocorre quando a frequência
alélica em um lócus trás informação sobre a de outro lócus”
ou do livro: “Linkage disequilibrium is the condition in which the
haplotype frequencies in a population deviate from the values they
would have if the genes at each locus were combined at random”. O
conceito chave para essa parte é que refere-se à frequência com que
dois alelos ocorrem “juntos” (seja num cromossomo ou num gameta) em
relação ao esperado se a segregação fosse independente.

O coeficiente de desequilíbrio de ligação é definido como a
diferença na frequência observada de cada haplótipo com a
frequência esperada dadas as frequências alélicas.

$$
D = F_{AB} - F_A \times F_B
$$

Processos que geram DL incluem:

- seleção num lócus arrastando, por carona, alelos ligados

- seleção favorecendo uma combinação de alelos em dois loci

- o surgimento de um novo alelo por mutação

- deriva genética amostrando haplótipos de modo a gerar população em
que frequências das combinações é alterada em relação ao esperado

- migração, no caso de duas populações muito diferenciadas se misturarem
